######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 29 20:36:57 2017
######################################################################

TEMPLATE = app
TARGET = qmageview
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += exif.h image.h main.h photogrid.h
SOURCES += exif.cpp image.cpp main.cpp photogrid.cpp
RESOURCES += resources.qrc
FORMS += mainwindow.ui resize_dialog.ui photogrid_dialog.ui gridsetup_dialog.ui
